services:
  backend:
    container_name: backend
    build:
      context: ./backend
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /logs:/logs
    command: ./scripts/start.sh
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - '8000:8000'
    expose:
      - 8000
    networks:
      - cpq

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      LANG: ru_RU.UTF-8
      LANGUAGE: ru_RU.UTF-8
      LC_ALL: ru_RU.UTF-8
    ports:
      - '5432:5432'
    expose:
      - 5432
    networks:
      - cpq

volumes:
  postgres_data: {}

networks:
  cpq: