# Generated by Django 5.1.7 on 2025-03-20 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='attribute_items',
        ),
        migrations.RemoveField(
            model_name='condition',
            name='condition_items',
        ),
        migrations.CreateModel(
            name='ConditionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(verbose_name='Значение')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_items', to='configurator.condition', verbose_name='Условие')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_items', to='configurator.item', verbose_name='Элемент')),
            ],
        ),
    ]
